service: opencoach-pistolsquat

frameworkVersion: ">=1.9.0 <2.0.0"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.0
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:975304741183:table/*"

functions:
  createCompetitor:
    handler: competitors/create.create
    events:
      - http:
          path: competitors
          method: post
          cors: 'https://pistolsquat.opencoach.tech/'

  listCompetitors:
    handler: competitors/list.list
    events:
      - http:
          path: competitors
          method: get

  getCompetitor:
    handler: competitors/get.get
    events:
      - http:
          path: competitors/{id}
          method: get

  updateCompetitor:
    handler: competitors/update.update
    events:
      - http:
          path: competitors/{id}
          method: put

  deleteCompetitor:
    handler: competitors/delete.delete
    events:
      - http:
          path: competitors/{id}
          method: delete


